name: Call Static JSON Files

on:
  push:
    branches:
      - circle-project-setup

jobs:
  call-json-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install ethers

      - name: Execute JSON Script
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}  # If needed for transactions
        run: |
          node scripts/your-script.js
