[API]
Address = "localhost:8086"
Explorer = true
UpdateMetricsInterval = "10s"
UpdateRecommendedFeeInterval = "10s"

[PriceUpdater]
Interval = "10s"
URL = "https://api-pub.bitfinex.com/v2/"
Type = "bitfinexV2"

[Debug]
APIAddress = "localhost:12345"

[StateDB]
Path = "/tmp/iden3-test/hermez/statedb"

[PostgreSQL]
Port     = 5432
Host     = "localhost"
User     = "hermez"
Password = "yourpasswordhere"
Name     = "hermez"

[Web3]
URL = "http://localhost:8545"

[Synchronizer]
SyncLoopInterval = "1s"
StatsRefreshPeriod = "1s"

    [Synchronizer.StartBlockNum]
    Rollup = 19
    Auction = 17
    WDelayer = 15

[SmartContracts]
Rollup   = "0x8EEaea23686c319133a7cC110b840d1591d9AeE0"
Auction  = "0x317113D2593e3efF1FfAE0ba2fF7A61861Df7ae5"
WDelayer = "0x5E0816F0f8bC560cB2B9e9C87187BeCac8c2021F"
TokenHEZ = "0x5D94e3e7aeC542aB0F9129B9a7BAdeb5B3Ca0f77"
TokenHEZName = "Hermez Network Token"

    [Synchronizer.InitialVariables.Auction]
    DonationAddress = "0x0000000000000000000000000000000000000001"
    BootCoordinator = "0xb4124cEB3451635DAcedd11767f004d8a28c6eE7"
    BootCoordinatorURL = "https://boot.coordinator.io"
    DefaultSlotSetBid = [
        "10000000000000000000",
        "10000000000000000000",
        "10000000000000000000",
        "10000000000000000000",
        "10000000000000000000",
        "10000000000000000000",
    ]
    DefaultSlotSetBidSlotNum = 0
    ClosedAuctionSlots = 2
    OpenAuctionSlots = 4320
    AllocationRatio = [4000, 4000, 2000]
    Outbidding = 1000
    SlotDeadline = 20

    [Synchronizer.InitialVariables.WDelayer]
    # HermezRollupAddress        =
    HermezGovernanceAddress    = "0x0000000000000000000000000000000000000001"
    EmergencyCouncilAddress    = "0x0000000000000000000000000000000000000001"
    WithdrawalDelay            = 60
    EmergencyModeStartingTime  = 0
    EmergencyMode              = false

    [Synchronizer.InitialVariables.Rollup]
    FeeAddToken = "10"
    ForgeL1L2BatchTimeout = 10
    WithdrawalDelay = 1209600 # 60 * 60 * 24 * 7 * 2
    SafeMode = false
        [[Synchronizer.InitialVariables.Rollup.Buckets]]
        CeilUSD             = 0
        Withdrawals         = 0
        BlockWithdrawalRate = 0
        MaxWithdrawals      = 0
        [[Synchronizer.InitialVariables.Rollup.Buckets]]
        CeilUSD             = 0
        Withdrawals         = 0
        BlockWithdrawalRate = 0
        MaxWithdrawals      = 0
        [[Synchronizer.InitialVariables.Rollup.Buckets]]
        CeilUSD             = 0
        Withdrawals         = 0
        BlockWithdrawalRate = 0
        MaxWithdrawals      = 0
        [[Synchronizer.InitialVariables.Rollup.Buckets]]
        CeilUSD             = 0
        Withdrawals         = 0
        BlockWithdrawalRate = 0
        MaxWithdrawals      = 0
        [[Synchronizer.InitialVariables.Rollup.Buckets]]
        CeilUSD             = 0
        Withdrawals         = 0
        BlockWithdrawalRate = 0
        MaxWithdrawals      = 0


[Coordinator]
ForgerAddress = "0x6BB84Cc84D4A34467aD12a2039A312f7029e2071"
ConfirmBlocks = 10
L1BatchTimeoutPerc = 0.6
ProofServerPollInterval = "1s"
SyncRetryInterval = "1s"

[Coordinator.L2DB]
SafetyPeriod = 10
MaxTxs       = 512
TTL          = "24h"
PurgeBatchDelay = 10
InvalidateBatchDelay = 20
PurgeBlockDelay = 10
InvalidateBlockDelay = 20

[Coordinator.TxSelector]
Path = "/tmp/iden3-test/hermez/txselector"

[Coordinator.BatchBuilder]
Path = "/tmp/iden3-test/hermez/batchbuilder"

[[Coordinator.ServerProofs]]
URL = "http://localhost:3000"

[Coordinator.EthClient]
CallGasLimit        = 300000
DeployGasLimit      = 1000000
GasPriceDiv         = 100
ReceiptTimeout      = "60s"
ReceiptLoopInterval = "500ms"

CheckLoopInterval = "500ms"
Attempts = 8
AttemptsDelay = "200ms"

[Coordinator.API]
Coordinator = true

[Coordinator.Debug]
BatchPath = "/tmp/iden3-test/hermez/batchesdebug"
