[API]
Address = "localhost:8086"
Explorer = true
UpdateMetricsInterval = "10s"
UpdateRecommendedFeeInterval = "10s"

[Debug]
APIAddress = "localhost:12345"

[StateDB]
Path = "/tmp/iden3-test/hermez/statedb"

[PostgreSQL]
Port     = 5432
Host     = "localhost"
User     = "hermez"
Password = "yourpasswordhere"
Name     = "hermez"

[Web3]
URL = "http://localhost:8545"

[Synchronizer]
SyncLoopInterval = "1s"
StatsRefreshPeriod = "1s"

[SmartContracts]
Rollup   = "0x8EEaea23686c319133a7cC110b840d1591d9AeE0"
Auction  = "0x317113D2593e3efF1FfAE0ba2fF7A61861Df7ae5"
WDelayer = "0x5E0816F0f8bC560cB2B9e9C87187BeCac8c2021F"
TokenHEZ = "0x5D94e3e7aeC542aB0F9129B9a7BAdeb5B3Ca0f77"
TokenHEZName = "Hermez Network Token"

[Coordinator]
ForgerAddress = "0x6BB84Cc84D4A34467aD12a2039A312f7029e2071"
ConfirmBlocks = 10
L1BatchTimeoutPerc = 0.6
ProofServerPollInterval = "1s"
SyncRetryInterval = "1s"

[Coordinator.L2DB]
SafetyPeriod = 10
MaxTxs       = 512
TTL          = "24h"
PurgeBatchDelay = 10
InvalidateBatchDelay = 20
PurgeBlockDelay = 10
InvalidateBlockDelay = 20

[Coordinator.TxSelector]
Path = "/tmp/iden3-test/hermez/txselector"

[Coordinator.BatchBuilder]
Path = "/tmp/iden3-test/hermez/batchbuilder"

[[Coordinator.ServerProofs]]
URL = "http://localhost:3000"

[Coordinator.EthClient]
CallGasLimit        = 300000
DeployGasLimit      = 1000000
GasPriceDiv         = 100
ReceiptTimeout      = "60s"
ReceiptLoopInterval = "500ms"

CheckLoopInterval = "500ms"
Attempts = 8
AttemptsDelay = "200ms"

[Coordinator.API]
Coordinator = true

[Coordinator.Debug]
BatchPath = "/tmp/iden3-test/hermez/batchesdebug"
