[API]
Address = "localhost:8086"
Explorer = true
UpdateMetricsInterval = "10s"
UpdateRecommendedFeeInterval = "10s"

[PriceUpdater]
Interval = "10s"
URL = "https://api-pub.bitfinex.com/v2/"
Type = "bitfinexV2"

[Debug]
APIAddress = "localhost:12345"
MeddlerLogs = true

[StateDB]
Path = "/tmp/iden3-test/hermez/statedb"
Keep = 256

[PostgreSQL]
Port     = 5432
Host     = "localhost"
User     = "hermez"
Password = "yourpasswordhere"
Name     = "hermez"

[Web3]
URL = "http://localhost:8545"

[Synchronizer]
SyncLoopInterval = "1s"
StatsRefreshPeriod = "1s"

[SmartContracts]
Rollup   = "0x8EEaea23686c319133a7cC110b840d1591d9AeE0"
Auction  = "0x317113D2593e3efF1FfAE0ba2fF7A61861Df7ae5"
WDelayer = "0x5E0816F0f8bC560cB2B9e9C87187BeCac8c2021F"
TokenHEZ = "0x5D94e3e7aeC542aB0F9129B9a7BAdeb5B3Ca0f77"
TokenHEZName = "Hermez Network Token"

[Coordinator]
# ForgerAddress = "0x05c23b938a85ab26A36E6314a0D02080E9ca6BeD" # Non-Boot Coordinator
ForgerAddress = "0xb4124ceb3451635dacedd11767f004d8a28c6ee7" # Boot Coordinator
ConfirmBlocks = 10
L1BatchTimeoutPerc = 0.6
ProofServerPollInterval = "1s"
SyncRetryInterval = "1s"

[Coordinator.L2DB]
SafetyPeriod = 10
MaxTxs       = 512
TTL          = "24h"
PurgeBatchDelay = 10
InvalidateBatchDelay = 20
PurgeBlockDelay = 10
InvalidateBlockDelay = 20

[Coordinator.TxSelector]
Path = "/tmp/iden3-test/hermez/txselector"

[Coordinator.BatchBuilder]
Path = "/tmp/iden3-test/hermez/batchbuilder"

[[Coordinator.ServerProofs]]
URL = "http://localhost:3000/api"

[Coordinator.Circuit]
MaxTx = 512
NLevels = 32

[Coordinator.EthClient]
ReceiptTimeout      = "60s"
ReceiptLoopInterval = "500ms"

CheckLoopInterval = "500ms"
Attempts = 8
AttemptsDelay = "200ms"

[Coordinator.EthClient.Keystore]
Path = "/tmp/iden3-test/hermez/ethkeystore"
Password = "yourpasswordhere"

[Coordinator.API]
Coordinator = true

[Coordinator.Debug]
BatchPath = "/tmp/iden3-test/hermez/batchesdebug"
LightScrypt = true
