[API]
Address = "localhost:8086"
Explorer = true

[Debug]
APIAddress = "localhost:12345"

[StateDB]
Path = "/tmp/iden3-test/hermez/statedb"

[PostgreSQL]
Port     = 5432
Host     = "localhost"
User     = "hermez"
Password = "yourpasswordhere"
Name     = "hermez"

[Web3]
URL = "http://localhost:8545"

[Synchronizer]
SyncLoopInterval = "1s"
StatsRefreshPeriod = "1s"

    [Synchronizer.StartBlockNum]
    Rollup = 1
    Auction = 1
    WDelayer = 1

[SmartContracts]
Rollup   = "0x6F4e99522F4eB37e0B73D0C0373147893EF12fD5"
Auction  = "0x5E0816F0f8bC560cB2B9e9C87187BeCac8c2021F"
WDelayer = "0x5D94e3e7aeC542aB0F9129B9a7BAdeb5B3Ca0f77"
TokenHEZ = "0x2b7dEe2CF60484325716A1c6A193519c8c3b19F3"
TokenHEZName = "Hermez Network Token"

    [Synchronizer.InitialVariables.Auction]
    DonationAddress = "0x0000000000000000000000000000000000000001"
    BootCoordinator = "0xb4124cEB3451635DAcedd11767f004d8a28c6eE7"
    DefaultSlotSetBid = [
        "10000000000000000000",
        "10000000000000000000",
        "10000000000000000000",
        "10000000000000000000",
        "10000000000000000000",
        "10000000000000000000",
    ]
    ClosedAuctionSlots = 2
    OpenAuctionSlots = 4320
    AllocationRatio = [4000, 4000, 2000]
    Outbidding = 1000
    SlotDeadline = 20

    [Synchronizer.InitialVariables.WDelayer]
	# HermezRollupAddress        =
	HermezGovernanceDAOAddress = "0x0000000000000000000000000000000000000001"
	WhiteHackGroupAddress      = "0x0000000000000000000000000000000000000001"
	HermezKeeperAddress        = "0x0000000000000000000000000000000000000001"
	WithdrawalDelay            = 60
	EmergencyModeStartingTime  = 0
	EmergencyMode              = false

    [Synchronizer.InitialVariables.Rollup]
    FeeAddToken = "10"
    ForgeL1L2BatchTimeout = 10
    WithdrawalDelay = 1209600 # 60 * 60 * 24 * 7 * 2
        # [[Synchronizer.InitialVariables.Rollup.Buckets]]
        # CeilUSD             = 0
        # BlockStamp          = 0
        # Withdrawals         = 0
        # BlockWithdrawalRate = 0
        # MaxWithdrawals      = 0
        # [[Synchronizer.InitialVariables.Rollup.Buckets]]
        # CeilUSD             = 0
        # BlockStamp          = 0
        # Withdrawals         = 0
        # BlockWithdrawalRate = 0
        # MaxWithdrawals      = 0
        # [[Synchronizer.InitialVariables.Rollup.Buckets]]
        # CeilUSD             = 0
        # BlockStamp          = 0
        # Withdrawals         = 0
        # BlockWithdrawalRate = 0
        # MaxWithdrawals      = 0
        # [[Synchronizer.InitialVariables.Rollup.Buckets]]
        # CeilUSD             = 0
        # BlockStamp          = 0
        # Withdrawals         = 0
        # BlockWithdrawalRate = 0
        # MaxWithdrawals      = 0
        # [[Synchronizer.InitialVariables.Rollup.Buckets]]
        # CeilUSD             = 0
        # BlockStamp          = 0
        # Withdrawals         = 0
        # BlockWithdrawalRate = 0
        # MaxWithdrawals      = 0
